pantos-io/servicenode

pantos/servicenode/business/plugins.py
pantos/servicenode/celery.py
tests/business/test_plugins.py

The queue which is supposed to be purge during startup might not exist after we switch from the old approach where we had a single queue for all the tasks.

[PAN-1927] queue purge error

---

pyproject.toml

Update version to 1.7.1
NA
NA
A new release should come after landed.

Update project version to 1.7.1

---

.github/workflows/release.yaml

Adds missing token to github publish pages
- Closes #

fix: PAN-1882 add github token

---

sonar-project.properties

The `scripts` folder can skip the sonarcloud analysis. 
NA
Quality gate at the sonarCloud analysis goes green.

[PAN-1929] Skip scripts on sonarcloud

---

.github/workflows/ci.yaml
.github/workflows/docker-vulnerabilities.yaml

Trivy analysis for Docker images included into the CI pipeline.
NA
Check CI triggers the Docker vulnerability analysis.

[PAN-1943] Trivy analysis for Docker

---

pantos/servicenode/application.py
tests/test_application.py

Check signer key validity on startup

feat: check signer key validity on startup

---

Makefile
pantos/servicenode/blockchains/base.py
pantos/servicenode/blockchains/ethereum.py
poetry.lock
pyproject.toml
tests/blockchains/test_ethereum.py

Introduce versioning for the smart contracts ABI.

[PAN-1994] adapt ABI versioning

---

.github/workflows/build.yml
.github/workflows/ci.yaml
.github/workflows/docker-vulnerabilities.yaml
.github/workflows/release.yaml
.github/workflows/sonar.yaml
poetry.lock

Hardening for CI workflow. In general all the third-party GitHub actions not coming from Pantos or the actions repo are pinned. 
- Closes #
QA should work as expected. 
Take into consideration that the `release` workflow can only be tested in the next release.

[PAN-2035] CI hardening

---

linux/scripts/start-web.py

Do not disclose running server command to be compliant with:
[CWE-312](https://cwe.mitre.org/data/definitions/312.html)
[CWE-359](https://cwe.mitre.org/data/definitions/359.html)
[CWE-532](https://cwe.mitre.org/data/definitions/532.html)

[PAN-2074] Do not disclose starting server command

---

debian/changelog
pyproject.toml

Sets release to 1.8.1
- Closes #

release: 1.8.1

---

pantos/servicenode/application.py
pantos/servicenode/configuration.py
pantos/servicenode/restapi.py
poetry.lock
pyproject.toml
tests/test_application.py
tests/test_configuration.py

Add the blockchain check endpoint

[PAN-2069] add blockchain rpcs check

---

.github/workflows/build.yml
.github/workflows/main.yaml
.github/workflows/publish-docker.yaml
.github/workflows/release.yaml

Deploys the containers to dockerhub with the `development` tag on merge to main.
- Related Issue #PAN-2078
- Closes #

feat: PAN-2078 deploy to dockerhub on main merge

---

.github/workflows/publish-docker.yaml

Please see the [associated discussion](https://github.com/orgs/community/discussions/124343). Apparently with upload/download v4 there's a problem when sharing artifacts across workflows.
- Closes #

fix: deploy development image on main merge

---

.github/workflows/ci.yaml
.github/workflows/main.yaml
.github/workflows/publish-docker.yaml
Makefile
README.md
debian/rules
environment.yml

Adds documentation and checks relating to using conda to build the debian package.
- Closes #

fix: add conda readme and environment

---

linux/scripts/start-web.py

Remove potential entry disclosing confidential data according to:
- https://cwe.mitre.org/data/definitions/312.html
- https://cwe.mitre.org/data/definitions/359.html
- https://cwe.mitre.org/data/definitions/532.html
This was already fixed #48  in and introduced again.

fix disclosing data command

---

.github/workflows/ci.yaml
.github/workflows/publish-docker.yaml
Makefile
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml
linux/scripts/pantos-service-node-celery

Adds docker swarm support.
- Related Issue #PAN-1832
- Closes #

feat: PAN-1832 add multiple local service nodes

---

.dockerignore
.github/workflows/ci.yaml
Dockerfile

Switches to the development version for ethereum contracts.
- Closes #

fix: switch to dev version for eth contracts

---

.github/workflows/main.yaml
.github/workflows/publish-docker.yaml
.github/workflows/release.yaml
docker-compose.yml

Changes the development image tag so that we can always reference the latest.
- Related Issue #PAN-1832
- Closes #

fix: PAN-1832 change dev image tag

---

.github/workflows/publish-docker.yaml

Restores ubuntu builder and adds multi-arch
- Closes #

fix: restore ubuntu build

---

.github/workflows/build.yml
.github/workflows/ci.yaml
.github/workflows/docker-vulnerabilities.yaml
.github/workflows/main.yaml
.github/workflows/publish-docker.yaml
.github/workflows/release.yaml
Dockerfile
Makefile
configurator/DEBIAN/.gitignore
debian/rules
environment.yml

feat: PAN-1832 multi arch builds

---

.github/workflows/docker-vulnerabilities.yaml

Sets harden to audit so as to get the new URLs required for conda-forge.
- Closes #

fix: docker vulns with conda forge

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/docker-vulnerabilities.yaml
.github/workflows/sonar.yaml
Makefile

Avoids a double docker build when running the CI workflow.
- Closes #

fix: avoid double docker build

---

pantos/servicenode/business/bids.py

Add extra info to bids log message

[PAN-2142] insufficient log message context

---

pantos/servicenode/blockchains/base.py
service-node-config.yml

We are adding the max_fee_per_gas field from the config back in. It has been commented out, since it seemed to be optional. Since the YAML tag directive does not support the or operation, 0 indicates None. 
PAN-2194
- Closes #

PAN-2194: Adding field back in

---

Makefile

fix: forces shell to be bash

---

.github/workflows/ci.yaml
Dockerfile

Fixes missing wheel after release pipeline changes.
- Closes #

fix: release pipeline build wheel

---

debian/changelog
pyproject.toml

fix: bump 2.0.1

---

configurator/DEBIAN/postinst
docker-compose.yml
poetry.lock
pyproject.toml
service-node-config.env
service-node-config.local.env
tests/database/conftest.py

Upgrade from psycopg2 to psycopg 3.x.

[PAN-2275] Upgrade psycopg

---

linux/scripts/start-web.py

Improve the logging when starting the web server

docs: improve start web server logging

---

debian/changelog
poetry.lock
pyproject.toml

fix: bump version 2.1.0

---

debian/changelog
poetry.lock
pyproject.toml

bump 2.1.2

---

.github/workflows/docker-vulnerabilities.yaml

Update trivy to 0.29.0 to unblock the vulnerabilities DB limitation.
- Closes #

Update trivy to 0.29.0

---

pantos/servicenode/blockchains/base.py
pantos/servicenode/blockchains/ethereum.py
pantos/servicenode/blockchains/solana.py
pantos/servicenode/business/base.py
pantos/servicenode/business/bids.py
pantos/servicenode/business/node.py
pantos/servicenode/business/plugins.py
pantos/servicenode/business/transfers.py
tests/blockchains/test_base.py
tests/blockchains/test_ethereum.py
tests/business/test_node.py

Prevent the submission of service node registration transactions that do not meet the requirements.

[PAN-2343] Node registration prerequisites checks

---

service-node-config.yml

feat: add sonic blaze rpc

---

.github/workflows/ci.yaml
.github/workflows/docker-vulnerabilities.yaml
.github/workflows/main.yaml
.github/workflows/publish-docker.yaml
service-node-config.yml

fix: update sonic blaze chain ID

---

debian/changelog
poetry.lock
pyproject.toml

doc: bump version

---

pantos/servicenode/application.py
pantos/servicenode/blockchains/base.py
pantos/servicenode/protocol.py
service-node-config.docker.env
service-node-config.env
service-node-config.local.env
service-node-config.yml
tests/test_application.py

We now check the Pantos protocol version compatibility of the Hub and Forwarder contracts at startup.

[PAN-2030] Protocol version of contracts
